### ISSUE TITLE
CDAClient.fetchSpace() fails if no access to master environment

### ISSUE THREAD

**Issue by zetlan** [contentful/contentful.java#180] opened 2018-12-12 20:42 UTC
I'm using environments to separate my staging & production systems. My staging service API key has access to my staging environment but not master; production has access to master but not staging. In the staging environment, a call to `CDAClient.fetchSpace()` produces an error:

```
{
  "sys": {
    "type": "Error",
    "id": "NotFound"
  },
  "message": "The resource could not be found.",
  "details": {
    "type": "Environment",
    "id": "master",
    "space": "77l22z9el0aa"
  },
  "requestId": "efb46a83e44146751c498e906c828250"
}
```

and you can see it's looking for the `master` environment, even though I called `.setEnvironment('staging')` when building the client. Other calls (e.g., to `.fetch(CDAEntry.class)` successfully query the staging environment.

**Comment by mariobodemann** [comment] 2019-01-03 10:55
Hello,

as stated in our _Contentful Community Slack_<sup><a href="https://www.contentful.com/slack/">invite link #sponsored</a></sup>, this is intended behaviour: An access token not having access to the space (as in not having access to the master environment) does not have access to `.fetchSpace()`.

To verify if you can access an environment please try and use ` .fetch(CDAEntry.class)` and then, assuming there are entries, you should get them. (If there are no entries, you sill might face an exception. In this case, let us find a better different way together.)

**Comment by mariobodemann** [comment] 2019-01-28 14:49
I am going to close this issue for now. If any unclarities continue to exist, please create a new issue, or comment here.

**Closed by mariobodemann** 2019-01-28 14:49 UTC
