### ISSUE TITLE
Inconsistent ordering of entries (Android vs iOS)

### ISSUE THREAD

**Issue by mhelder** [contentful/contentful.java#176] opened 2018-08-13 15:15 UTC
Consider the following scenario:

We have an array with one item (entry), which has a property (`screens`) that is basically a list of entries. These screens look like this in the array item:

```
"screens": [{
  "sys": {
    "type": "Link",
            "linkType": "Entry",
            "id": "4N8k..."
  }
}, {
  "sys": {
    "type": "Link",
            "linkType": "Entry",
            "id": "27S7..."
  }
}, {
  "sys": {
    "type": "Link",
            "linkType": "Entry",
            "id": "58De..."
  }
}]
```
The array item's `includes` contains all data for these screen entries:

```
"includes": {
  "Entry": [{
    "sys": {
      "id": "27S7...",
      ...
    },
    "fields": { ... }
  }, {
    "sys": {
      "id": "4N8k...",
      ...
    },
    "fields": { ... }
    }, {
      "sys": {
        "id": "58De...",
      ...
      },
      "fields": { ... }
    }]
}
``` 
Note how the order of the entries is different in these two json arrays (refer to the ids). Now, the iOS SDK seems to return the screen order as per the first json snippet (`screens`), however, the Android SDK appears to return the items in the order of the 2nd snippet (`includes.Entry`).

As a result, the item ordering is inconsistent between the two platforms. The is causing us some headaches with our `screens` data, as we initially intended our mobile clients to be driven by the order of items as returned from Contentful. But as the mobile SDKs exhibit different behaviour, this is unfortunately a no-go at the moment.

We can of course work around the problem by adding a property to enable explicit ordering/sorting on the clients, but this wouldn't be ideal for various reasons. 

Any chance this is something that could be looked into? At a minimum, having consistent behaviour across the mobile SDKs seems preferable. Or perhaps this is something that can be configured on the Contentful-side? (forgive my ignorance, as I'm primarily a consumer of the API data).

**Comment by mariobodemann** [comment] 2018-08-13 15:37
Hello,

I saw your are inspecting the `includes` array of the response. This field is not intended to contain the resources in-order, but rather store the resources for building up the model presented to the user.

Instead, what you probably want to do is fetch the item containing the `screens` by id and then inspect its `screens`-field:

```
final CDAEntry one =
    client
        .fetch(CDAEntry.class)
        .one("{insert-id-here}");

final Collection<CDAResource> screens = one.getField("en-US", "screens");
for (final CDAResource resource : screens) {
  System.out.println(resource.id());
}
```

The output will be like so:

```
A96usFSlY4G0W4kwAqswk
1asN98Ph3mUiCYIYiiqwko
1asN98Ph3mUiCYIYiiqwko
1asN98Ph3mUiCYIYiiqwko
A96usFSlY4G0W4kwAqswk
```

Using the `screens`-field of an entry will return the resources in order defined in Contentful and works across all SDKs. 

I hope that makes it a bit clearer on what is happening.

Greetings,
Mario

**Comment by mhelder** [comment] 2018-08-13 18:03
Hi Mario,

I appreciate the swift reply. Unfortunately, I can't fetch a specific item by ID; instead I have a query that fetches the first item with a certain content type. But regardless of the approach to get a specific item, I'm seeing the same inconsistency.

> I saw your are inspecting the includes array of the response. This field is not intended to contain the resources in-order, but rather store the resources for building up the model presented to the user.

I don't actually inspect the `includes` at runtime (it's a package-private field/class for a reason) :).  Because of the inconsistency between the iOS and Android SDK, I decided to look at the raw I/O. I was only then that I noticed there are two separate arrays that contain resources with IDs in different orders. I didn't deep-dive into the code of the SDK, but I can tell you that the `screens` are returned in these orders:

iOS:
```
let screens = entry.fields.linkedEntries(at: "screens")
```
Result: `[27S7, 4N8k, 58De]`

Android:
```
List<CDAEntry> entries = entry.getField("screens");
```
Result: `[4N8k, 27S7, 58De]`

> Using the screens-field of an entry will return the resources in order defined in Contentful and works across all SDKs.

For some reason, that doesn't appear to be true for me? Perhaps I'm missing something obvious here?

Cheers, Matt

**Comment by mariobodemann** [comment] 2018-08-14 07:42
Hey,

that sounds really odd to me and the swift SDK developer (@loudmouth). 

Maybe we can compare both sides of code you are using (swift and java) with a screenshot from the UI, so we see the order in Contentful and then the code using this order.

I'm sure together we can make sense on what is happening...

**Comment by loudmouth** [comment] 2018-08-14 07:44
Hey there, I'll just chime in that I'm a little confused after the first and last messages you left @mhelder ...In the first message you said the Swift SDK is returning the order as listed in the first JSON snippet which shows the `screens` field's jaw JSON; in the last message, you said the Swift SDK is returning you ID's in this order, `[27S7, 4N8k, 58De]`, which is _not_ the same order as the first JSON snippet. Can you help us by clarifying? We want to understand which SDK may be returning the wrong order so we can identify why.

**Comment by mhelder** [comment] 2018-08-14 08:25
@loudmouth: Ah, apologies. It looks like I messed up the original post by inverting that statement. Just to clarify, this is the gist of the json response from Contenful:

```
{
	"sys": {
		"type": "Array"
	},
	"items": [{
		"sys": {
			"id": "5nmZ",
			"type": "Entry"
		},
		"fields": {
			"title": "Demo",
			"screens": [{
				"sys": {
					"type": "Link",
					"linkType": "Entry",
					"id": "4N8k"
				}
			}, {
				"sys": {
					"type": "Link",
					"linkType": "Entry",
					"id": "27S7"
				}
			}, {
				"sys": {
					"type": "Link",
					"linkType": "Entry",
					"id": "58De"
				}
			}]
		}
	}],
	"includes": {
		"Entry": [{
			"sys": {
				"id": "27S7",
				"type": "Entry",

			},
			"fields": { }
		}, {
			"sys": {
				"id": "4N8k",
				"type": "Entry",
			},
			"fields": { }
		}, {
			
			"id": "58De",
			"type": "Entry",
			"fields": { }
		}]
	}
}
```
Then, retrieving the `screens` from the entry gives these results:

```
let screens = entry.fields.linkedEntries(at: "screens")
```
iOS: `[27S7, 4N8k, 58De]`

```
List<CDAEntry> entries = entry.getField("screens");
```
Android: `[4N8k, 27S7, 58De]`

So on iOS the order of screens matches that of the `includes`, on Android it's the order of the `fields.screens` (this is where I confused myself in the first post...sorry). 

Assuming we're calling the appropriate functions to retrieve the `screens` from the entry, it seems to me that either iOS or Android is ending up with the wrong order. My initial thought was that it's the Android SDK (hence the issue here) but to honest: I can't verify the order as configured in Contentful (have asked our customer to double check) so don't really have a clue which one is supposed to be correct. 

I guess the latter is what you guys could answer: which of the two orderings is supposed to reflect the actual ordering in Contentful?

I'm happy to provide more details if required. Just let me know what you need. Thanks for the prompt responses so far!

**Comment by loudmouth** [comment] 2018-08-14 09:26
Hi, this looks like an issue with [contentful.swift](https://github.com/contentful/contentful.swift) as the proper order is the one represented in the reference field of the parent object, not the order listed in the includes. The proper order _should_ be `[4N8k, 27S7, 58De]` as the real order of a one-to-many reference field is represented in the JSON response as the array of link objects at that field.

I was about to open a new Github issue on your behalf for the Swift project, but I'm wondering if you could do it instead @mhelder and fill out the new issue template available there so I can get info about what operating systems, package managers, & xcode versions you're using.

I'm going to close this issue for now.

**Comment by loudmouth** [comment] 2018-08-14 10:28
Hey @mhelder I'll add as an addendum that I've been doing more testing and I can't reproduce this issue on contentful.swift so far; nor can i see any suspicious code that would cause the ordering to get out of sync like that.

The `linkedEntries(at:)` method directly maps array of links to entries so the order shouldn't be changed and I don't think it is changed any earlier (during JSON deserialization).

**Comment by loudmouth** [comment] 2018-08-14 10:46
I have one suspicion as to why this may be happening in Swift. When you make your Github issue, can you please share the code you have for your Query against the API please?

**Comment by mhelder** [comment] 2018-08-15 12:40
Good news: our customer has confirmed the `screens` are actually in the same order as exposed by the Android SDK (`[4N8k, 27S7, 58De]`). And as it turns out, the same is actually true for the iOS SDK...

I hate to admit it, but the problem was all on our end (a combination of assumptions, unknowns and business logic), and there was no issue with the SDK(s) to begin with. 

My sincere apologies for the waste of time. 😞

**Comment by mariobodemann** [comment] 2018-08-15 12:50
Hey,

no worries, we are just happy to hear you could solve the issue. If you can find the time and think about what would have made the journey easier on our side, I am happy to read your thoughts.

But till then, I will close this issue, and feel free to reach out to us any time you need us.

Greetings,
Mario

**Closed by mariobodemann** 2018-08-15 12:50 UTC

**Comment by loudmouth** [comment] 2018-08-15 13:13
As Mario said, no worries @mhelder ! Just glad we got everything all sorted out :-)
